pipeline {
    agent none
    stages {
        stage('build') {
            agent { master }
            steps { git 'https://github.com/zxslinux/deploy.git' }
            steps { sh 'cd redis-cluster && bash build.sh 3.2.12' }
        }
    }
}