# 停止 haproxy
- name: stop haproxy
  service:
    name: haproxy
    enabled: false
    state: stopped

# 卸载 haproxy
- name: uninstall haproxy by yum
  yum:
    name: haproxy
    state: removed
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags:
    - uninstall