### 用于安装后执行
# 分发 安全设置脚本
- name: copy secure_setup.sql
  template:
    src: secure_setup.sql.j2
    dest: /root/secure_setup.sql
  tags:
    - install
  when: role=='master'

# 执行安全设置脚本
- name: exec secure setup sql
  shell: /usr/local/mysql/bin/mysql < /root/secure_setup.sql
  when: role=='master'