- name: delete link to es install path
  file:
    path: "{{ es.install_path }}/elasticsearch-{{ es.version }}"
    state: absent 

- name: delete es systemd service file
  file:
    path: /usr/lib/systemd/system/elasticsearch.service
    state: absent

- name: delete system user
  user:
    name: {{ es.user }}
    state: absent
    remove: yes
