Vagrant.configure("2") do |config|
  config.vm.provision "shell", path: "/opt/vm/init-os.sh"
  config.vm.define :ha01 do |ha01|
    ha01.vm.box = "centos7"
    ha01.vm.hostname = "ha01"
    ha01.vm.network :private_network, ip: "192.168.1.12"
  end
  config.vm.define :ha02 do |ha02|
    ha02.vm.box = "centos7"
    ha02.vm.hostname = "ha02"
    ha02.vm.network :private_network, ip: "192.168.1.13"
  end

end